name: Deploy

on:
  push:
    branches:
      - main

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create Symlink for Prisma Files
        run: |
          ./link.sh
      - name: Install Dependencies
        env:
          CI: true
        run: |
          cd processor
          npm ci
      - name: Migrate Database
        run: |
          cd processor
          npx prisma migrate deploy
      - name: Deploy
        run: |
          cd processor
          npx ncc build src/index.ts
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=Regeneron-Processor-S3-Trigger --zip-file=fileb://deploy.zip
